[package]
name = "xrvis-vr"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
name = "xrvis_vr"
crate-type = ["lib", "cdylib"]

[dependencies]
bevy.workspace = true
bevy_mod_openxr.workspace = true
bevy_mod_xr.workspace = true
sslgame.workspace = true
